Add icon support
infotexture/dita-bootstrap pull request #11
Opened 2021-07-09 09:52 UTC by jason-fox

- Update Plugin Code
- Update Docs
- Add Sample Footer with icons

![Screenshot 2021-07-09 at 11 44 59](https://user-images.githubusercontent.com/3439249/125059764-f9ce2c00-e0ab-11eb-8299-8750d752d6c1.png)

2021-08-22 17:34 UTC, infotexture requested changes
When I check out this branch and build the DITA-OT docs as sample output, the build fails with XSLT errors:

```console
[xslt] Error evaluating ($BOOTSTRAP_ICONS_CDN) at procedure BOOTSTRAP_ICONS_CDN on line 15 of html5-bootstrap.xsl:
[xslt]   XTDE0700: A value must be supplied for parameter $BOOTSTRAP_ICONS_CDN because there is no
[xslt]   default value for the required type
```

This can probably be avoided by specifying the missing value, but this shouldn't be **required**.

Not everyone will want or need these icons, so it should still be possible to build output without them.

2021-08-22 17:40 UTC, infotexture commented on sample/icons.dita
> +    DITA Bootstrap includes the Bootstrap Icons set by default. Other Icon libraries such as
```suggestion
    DITA Bootstrap includes Bootstrap Icons by default. Other icon libraries
```

2021-08-22 18:12 UTC, jason-fox commented on sample/icons.dita
> +    DITA Bootstrap includes the Bootstrap Icons set by default. Other Icon libraries such as
Fixed cfe1e62

2021-08-22 18:14 UTC, jason-fox commented
> When I check out this branch and build the DITA-OT docs as sample output, the build fails with XSLT errors:

It wasn't erroring for me, so maybe a Windows issue. The default had been left as `'yes'` rather than `'no'` and I've moved the CDN PATH into the if clause. Hopefully fixed cfe1e62

2021-08-23 22:12 UTC, infotexture commented on .github/dita-ot/header.xml
> +          <path transform="matrix(0.07083334 0 0 0.07083334 -0 -0)"  d="M66.86719 0.11132812C 29.708588 0.11132812 -0.20703125 30.025093 -0.20703125 67.18359L-0.20703125 67.18359L-0.20703125 413.0371
I like the idea of including a logo here in the header, but we shouldn't use the DITA-OT logo, as this is a separate project.

I'll push a commit to replace this with the Bootstrap “B” as a placeholder for now.

2021-08-23 22:15 UTC, infotexture approved these changes

2021-08-23 22:16 UTC, merged

2021-08-23 22:40 UTC, infotexture commented
P.S. I'd been meaning to add the DITA-OT logo to the header on the project website at dita-ot.org. 

Tested in my local fork and looks good, so I'll tweak a bit more and submit a PR to include it there.